GovUkDesignSystemDotNetDemo/Models/ExampleViewModel.cs
namespace GovUkDesignSystemDotNetDemo.Models;

public class ExampleViewModel
{
    public string ExampleName { get; set; }
    public string Code { get; set; }
}

GovUkDesignSystemDotNetDemo/Models/InteractiveExampleViewModel.cs
namespace GovUkDesignSystemDotNetDemo.Models;

public class InteractiveExampleViewModel
{
    public string ExampleHref { get; set; }
    public List<InteractiveExampleCodeSnippetViewModel> CodeSnippets { get; set; } = [];
}

public class InteractiveExampleCodeSnippetViewModel
{
    public string Title { get; set; }
    public string Filename { get; set; }
    public string Code { get; set; }
}

GovUkDesignSystemDotNetDemo/Controllers/ComponentsController.cs
using Microsoft.AspNetCore.Mvc;

namespace GovUkDesignSystemDotNetDemo.Controllers;

[Route("components")]
public class ComponentsController : Controller
{
    [HttpGet("")]
    public IActionResult Index() => View();

    [HttpGet("back-link")]
    public IActionResult BackLink() => View();

    [HttpGet("breadcrumbs")]
    public IActionResult Breadcrumbs() => View();

    [HttpGet("button")]
    public IActionResult Button() => View();

    [HttpGet("character-count")]
    public IActionResult CharacterCount() => View();

    [HttpGet("checkbox-item")]
    public IActionResult CheckboxItem() => View();

    [HttpGet("checkboxes")]
    public IActionResult Checkboxes() => View();

    [HttpGet("error-message")]
    public IActionResult ErrorMessage() => View();

    [HttpGet("error-summary")]
    public IActionResult ErrorSummary() => View();

    [HttpGet("fieldset")]
    public IActionResult Fieldset() => View();

    [HttpGet("file-upload")]
    public IActionResult FileUpload() => View();

    [HttpGet("footer")]
    public IActionResult Footer() => View();

    [HttpGet("header")]
    public IActionResult Header() => View();

    [HttpGet("hint")]
    public IActionResult Hint() => View();

    [HttpGet("label")]
    public IActionResult Label() => View();

    [HttpGet("phase-banner")]
    public IActionResult PhaseBanner() => View();

    [HttpGet("radio-item")]
    public IActionResult RadioItem() => View();

    [HttpGet("radios")]
    public IActionResult Radios() => View();

    [HttpGet("service-navigation")]
    public IActionResult ServiceNavigation() => View();

    [HttpGet("tag")]
    public IActionResult Tag() => View();

    [HttpGet("textarea")]
    public IActionResult Textarea() => View();

    [HttpGet("text-input")]
    public IActionResult TextInput() => View();

    [HttpGet("examples/{exampleName}")]
    public IActionResult ExamplePage(string exampleName)
    {
        return View(exampleName);
    }
}

GovUkDesignSystemDotNetDemo/Controllers/InteractiveComponentsController.cs
using GovUkDesignSystemDotNetDemo.Models.InteractiveComponentsExamples;
using Microsoft.AspNetCore.Mvc;

namespace GovUkDesignSystemDotNetDemo.Controllers;

[Route("interactive-components")]
public class InteractiveComponentsController : Controller
{
    [HttpGet("")]
    public IActionResult Index() => View();

    
    [HttpGet("character-count-for")]
    public IActionResult CharacterCountFor() => View();

    [Route("CharacterCountForExampleDefault")]
    public IActionResult CharacterCountForExampleDefault(CharacterCountForExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("checkbox-item-for")]
    public IActionResult CheckboxItemFor() => View();

    [Route("CheckboxItemForExampleDefault")]
    public IActionResult CheckboxItemForExampleDefault(CheckboxItemForExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("checkboxes-for")]
    public IActionResult CheckboxesFor() => View();

    [Route("CheckboxesForExampleDefault")]
    public IActionResult CheckboxesForExampleDefault(CheckboxesForExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("checkboxes-from-strings-for")]
    public IActionResult CheckboxesFromStringsFor() => View();

    [Route("CheckboxesFromStringsForExampleDefault")]
    public IActionResult CheckboxesFromStringsForExampleDefault(CheckboxesFromStringsForExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("error-summary-if-needed")]
    public IActionResult ErrorSummaryIfNeeded() => View();

    [Route("ErrorSummaryIfNeededExampleDefault")]
    public IActionResult ErrorSummaryIfNeededExampleDefault(ErrorSummaryIfNeededExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("file-upload-for")]
    public IActionResult FileUploadFor() => View();

    [Route("FileUploadForExampleDefault")]
    public IActionResult FileUploadForExampleDefault(FileUploadForExampleDefaultViewModel vm) => ExampleDefault(vm,
        () =>
        {
            if (vm.YourCsvFile == null)
            {
                ModelState.AddModelError(nameof(vm.YourCsvFile), "Upload a CSV file");
            }
        });

    [HttpGet("textarea-for")]
    public IActionResult TextareaFor() => View();

    [Route("TextareaForExampleDefault")]
    public IActionResult TextareaForExampleDefault(TextareaForExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("text-input-for")]
    public IActionResult TextInputFor() => View();

    [Route("TextInputForExampleDefault")]
    public IActionResult TextInputForExampleDefault(TextInputForExampleDefaultViewModel vm) => ExampleDefault(vm);

    [HttpGet("radios-for")]
    public IActionResult RadiosFor() => View();

    [Route("RadiosForExampleDefault")]
    public IActionResult RadiosForExampleDefault(RadiosForExampleDefaultViewModel vm) => ExampleDefault(vm);

    
    private IActionResult ExampleDefault<TViewModel>(TViewModel viewModel, Action extraValidation = null)
    where TViewModel : new()
    {
        string actionName = ControllerContext.RouteData.Values["action"].ToString();
        
        switch (Request.Method)
        {
            case "GET":
                ModelState.Clear();
                return View(actionName, new TViewModel());

            case "POST":
                if (extraValidation != null)
                {
                    extraValidation();
                }
                
                if (!ModelState.IsValid)
                {
                    return View(actionName, viewModel);
                }

                return View("InteractiveExampleValidationSuccessful");
            
            default:
                return StatusCode(StatusCodes.Status405MethodNotAllowed);
        }
    }
}

GovUkDesignSystemDotNetDemo/Views/Shared/Example.cshtml
@using GovUkDesignSystemDotNetDemo.Helpers
@model GovUkDesignSystemDotNetDemo.Models.ExampleViewModel

<div class="example-box">
    <div class="example-box-link">
        <p class="govuk-body-s govuk-!-margin-0">
            <a href="@(Url.Action("ExamplePage", "Components", new { exampleName = Model.ExampleName }))"
               target="_blank"
               class="govuk-link">
                Open this example in a new tab
            </a>
        </p>
    </div>
    <div class="example-box-example">
        <iframe src="@(Url.Action("ExamplePage", "Components", new { exampleName = Model.ExampleName }))"
                onload="resizeExampleIFrame(this)"
                ></iframe>
    </div>
    <div class="example-box-code">
        <pre><code class="language-csharp">@(CodeFormattingHelper.RemoveUnwantedWhitespace(Model.Code))</code></pre>
    </div>
</div>

GovUkDesignSystemDotNetDemo/Views/Shared/InteractiveExample.cshtml
@using GovUkDesignSystemDotNetDemo.Helpers
@using GovUkDesignSystemDotNetDemo.Models
@model GovUkDesignSystemDotNetDemo.Models.InteractiveExampleViewModel

<div class="example-box">
    <div class="example-box-link">
        <p class="govuk-body-s govuk-!-margin-0">
            <a href="@(Model.ExampleHref)"
               target="_blank"
               class="govuk-link">
                Open this example in a new tab
            </a>
        </p>
    </div>
    <div class="example-box-example">
        <iframe src="@(Model.ExampleHref)"
                onload="resizeExampleIFrame(this)"
        ></iframe>
    </div>
    
    @foreach (InteractiveExampleCodeSnippetViewModel codeSnippet in Model.CodeSnippets)
    {
        @if (!string.IsNullOrWhiteSpace(codeSnippet.Title))
        {
            <h4 class="govuk-heading-s example-box-title">
                <span class="govuk-!-padding-right-4">
                    @(codeSnippet.Title)
                </span>

                @if (!string.IsNullOrWhiteSpace(codeSnippet.Filename))
                {
                    <span class="govuk-!-font-weight-regular">
                        @(codeSnippet.Filename)
                    </span>
                }
            </h4>
        }
        <div class="example-box-code">
            <pre><code class="language-csharp">@(CodeFormattingHelper.RemoveUnwantedWhitespace(codeSnippet.Code))</code></pre>
        </div>
    }
</div>

GovUkDesignSystemDotNetDemo/Views/Shared/InteractiveExampleValidationSuccessful.cshtml
@using Microsoft.AspNetCore.Http.Extensions

@{
    Layout = "_LayoutForExamples";
}

<h1 class="govuk-heading-l">
    Validation successful
</h1>

<p class="govuk-body">
    <a href="@(Context.Request.GetDisplayUrl())"
       class="govuk-link">
        Start again
    </a>
</p>

GovUkDesignSystemDotNetDemo/Views/Shared/_Layout.cshtml
@using GovUkDesignSystemDotNet
@using Microsoft.AspNetCore.Http.Extensions

<!DOCTYPE html>
<html lang="en" class="govuk-template govuk-template--rebranded">

<head>
    <meta charset="utf-8">
    <title>
        @(!string.IsNullOrWhiteSpace(ViewBag.Title) ? $"{ViewBag.Title} - " : "")
        C#/.Net library for Gov.UK Design System
        - GOV.UK
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#1d70b8">
    <link rel="icon" sizes="48x48" href="/assets/rebrand/images/favicon.ico">
    <link rel="icon" sizes="any" href="/assets/rebrand/images/favicon.svg" type="image/svg+xml">
    <link rel="mask-icon" href="/assets/rebrand/images/govuk-icon-mask.svg" color="#1d70b8">
    <link rel="apple-touch-icon" href="/assets/rebrand/images/govuk-icon-180.png">
    <link rel="manifest" href="/assets/rebrand/manifest.json">
    <meta property="og:image" content="<SERVICE URL>/assets/rebrand/images/govuk-opengraph-image.png">
    <link rel="stylesheet" href="/stylesheets/govuk-frontend-5.10.2.min.css">
    <style>
        code {
            font-family: ui-monospace,menlo,"Cascadia Mono","Segoe UI Mono",consolas,"Liberation Mono",monospace;
            background-color: #f3f2f1;
            line-height: 1.25;
            color: #003078;
        }
        td code {
            color: #d13118;
            padding: 2px 4px;
            font-size: 1rem;
        }
        caption code, h3 code {
            color: #d13118;
            padding: 2px 4px;
        }

        .example-box {
            border: 1px solid #b1b4b6;
            margin-bottom: 40px;
        }
        .example-box div {
            border-bottom: 1px solid #b1b4b6;
        }
        .example-box div:last-child {
            border-bottom: none;
        }
        .example-box .example-box-link {
            padding: 10px;
        }
        .example-box .example-box-example iframe {
            border: 0;
            width: 100%;
        }
        .example-box .example-box-title {
            padding: 10px 10px 0;
            margin: 0 !important;
        }
        .example-box .example-box-code {
            padding: 10px;
        }
        .example-box .example-box-code pre {
            margin: 0;
        }
        .example-box .example-box-code pre code {
            display: block;
            overflow-x: auto;
            padding: 20px;
            font-size: 16px;
            background-color: #f3f2f1;
        }
    </style>
    <script>
        function resizeExampleIFrame(iframeElement) {
            const iframeBody = iframeElement.contentWindow.document.documentElement.querySelector('body');
            
            function doResize(iframeElement) {
                console.log('Resizing iframe', iframeElement);
                const innerContentHeight = iframeBody.scrollHeight;
                console.log(`New size ${innerContentHeight}px`, iframeElement);
                iframeElement.style.height = innerContentHeight + 'px';
                console.log('Resized iframe', iframeElement);
            }
            
            doResize(iframeElement);

            new ResizeObserver(() => doResize(iframeElement)).observe(iframeBody)
        }
    </script>
</head>

<body class="govuk-template__body">
    <script>
        document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? ' govuk-frontend-supported' : '');
    </script>

    <a href="#main-content" class="govuk-skip-link" data-module="govuk-skip-link">Skip to main content</a>

    @await Html.GovUkHeader(new HeaderViewModel
    {
        HomepageUrl = "https://gov.uk"
    })
    
    @await Html.GovUkServiceNavigation(new ServiceNavigationViewModel
    {
        ServiceName = "Design System in C#",
        ServiceUrl = Url.Action("Index", "Home"),
        NavigationItems = new List<ServiceNavigationItemViewModel>
        {
            new ServiceNavigationItemViewModel
            {
                HtmlOrText = new HtmlOrText("Components"),
                Href = Url.Action("Index", "Components"),
                Current = Context.Request.Path.StartsWithSegments(new PathString(Url.Action("Index", "Components"))),
                Active = Context.Request.Path.Equals(new PathString(Url.Action("Index", "Components")))
            },
            new ServiceNavigationItemViewModel
            {
                HtmlOrText = new HtmlOrText("Interactive components"),
                Href = Url.Action("Index", "InteractiveComponents"),
                Current = Context.Request.Path.StartsWithSegments(new PathString(Url.Action("Index", "InteractiveComponents"))),
                Active = Context.Request.Path.Equals(new PathString(Url.Action("Index", "InteractiveComponents")))
            },
        }
    })

    @await Html.GovUkPhaseBanner(new PhaseBannerViewModel
    {
        Tag = new TagViewModel
        {
            HtmlOrText = new HtmlOrText("Beta")
        },
        HtmlOrText = new HtmlOrText("This is a new service."),
        Classes = ["govuk-width-container"]
    })
    
    <div class="govuk-width-container">
        @(RenderSection("BeforeMain", false))
        
        <main class="govuk-main-wrapper" id="main-content">
            @RenderBody()
        </main>
    </div>
    
    @await Html.GovUkFooter(new FooterViewModel())

    <script type="module" src="/javascripts/govuk-frontend-5.10.2.min.js"></script>
    <script type="module">
        import {
            initAll
        } from '/javascripts/govuk-frontend-5.10.2.min.js'
        initAll()
    </script>
</body>

</html>

GovUkDesignSystemDotNetDemo/Views/Shared/_LayoutForExamples.cshtml
<!DOCTYPE html>
<html lang="en" class="govuk-template govuk-template--rebranded">

<head>
    <meta charset="utf-8">
    <title>GOV.UK - C#/.Net library for Gov.UK Design System</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="theme-color" content="#1d70b8">
    <link rel="icon" sizes="48x48" href="/assets/rebrand/images/favicon.ico">
    <link rel="icon" sizes="any" href="/assets/rebrand/images/favicon.svg" type="image/svg+xml">
    <link rel="mask-icon" href="/assets/rebrand/images/govuk-icon-mask.svg" color="#1d70b8">
    <link rel="apple-touch-icon" href="/assets/rebrand/images/govuk-icon-180.png">
    <link rel="manifest" href="/assets/rebrand/manifest.json">
    <meta property="og:image" content="<SERVICE URL>/assets/rebrand/images/govuk-opengraph-image.png">
    <link rel="stylesheet" href="/stylesheets/govuk-frontend-5.10.2.min.css">
</head>

<body class="govuk-template__body govuk-!-padding-6">
    <script>
        document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? ' govuk-frontend-supported' : '');
    </script>

    @RenderBody()
    
    <script type="module" src="/javascripts/govuk-frontend-5.10.2.min.js"></script>
    <script type="module">
        import {
            initAll
        } from '/javascripts/govuk-frontend-5.10.2.min.js'
        initAll()
    </script>
</body>

</html>